---
RecipeFormatVersion: "2020-01-25"
ComponentName: "com.custom.edge_application"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentType: "aws.greengrass.generic"
ComponentDescription: "This is a custom edge component."
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentDependencies:
  com.custom.aws_otel_collector:
    VersionRequirement: ">=1.0.0"
    DependencyType: "HARD"
Manifests:
- Platform:
    os: "all"
  Lifecycle:
    Install:
      Script: "python3 -m venv venv\n. venv/bin/activate\npip3 install --upgrade pip\n\
        pip3 install opentelemetry-sdk==1.11.1 opentelemetry-sdk-extension-aws~=2.0\
        \ opentelemetry-propagator-aws-xray~=1.0 opentelemetry-exporter-otlp==1.11.1\
        \ protobuf==3.20.* boto3"
    Run:
      Script: ". venv/bin/activate\nsleep 5 && python3 -u {artifacts:decompressedPath}/com.custom.edge_application/main.py"
  Artifacts:
  - Uri: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/com.custom.edge_application.zip"
    Unarchive: "ZIP"
